### PR TITLE
added support for taggables

### PR DESCRIPTION
**Pull request by karticbedi**
Can be used by chaining `->taggable()` method.

on form submition user need to create resource via fillFields method.

new value will be pushed to array as following for lable and value

`label:"newvalue"
value:"false-newvalue"
`

each new taggable value will have string prefix `false-` attached to it so user can filter that as following.

**Add field**

Multiselect::make('Publishers', 'publishers')
            ->placeholder('Select Publisher')
            ->belongsToMany(User::class)
            ->optionsLimit(5)
            ->options($this->getPublishers())
            ->singleSelect()
            ->taggable(),

**Create new resource**

```
protected static function fillFields(NovaRequest $request, $model, $fields){
    
    $pivot = $request->only(['publisher']);
    
    foreach ($pivot['publisher'] as $lable => $value) {
    	if(Str::contains($value, 'false-')){
            $newUserId =  self::createUserBy($value);
            $pivot['publisher'][$lable] = $newUserId;
        }
    }

    $request->request->set('publisher',$pivot['publisher'])

     return  $result = parent::fillFields($request, $model, $fields);
}

public static function createUserBy($tempUserId){
    $newUserName = Str::of($tempUserId)->replace('false-', '')->__toString();
    $user = new \App\Models\User();
    $user->password = \Hash::make('secret');
    $user->email = str_replace(' ', '', $newUserName).'.'.Str::random(4).'@example.com';
    $user->name = $newUserName;
    $user->save();
    return $user->id;
}
```

It will work with both multiple and single values.

### CODE REVIEW

**Comment by karticbedi** [comment]
any here care about the taggables?

**Comment by Tarpsvo** [comment]
Hi! I'll look this over in a second. Just some questions first: why the `false-` prefix? Why not just use an array where both the key and value are the same?

Thanks!

**Comment by Ken-vdE** [comment]
I need this exact functionality. Why has this not been merged yet?

**Comment by NoahNxT** [comment]
Any updates on this?

**Comment by Tarpsvo** [comment]
It's now released in version 2.4.0 and will be released in 3.0 as well for Nova 4. Thanks!

**Pull request closed without merging**
